task: test
validation_pairs: 500
visualize: False

scene_covisibility_threshold:
  brandenburg_gate: 0.1
  british_museum: 0.1
  buckingham_palace: 0.1
  colosseum_exterior: 0.1
  grand_place_brussels: 0.1
  lincoln_memorial_statue: 0.1
  notre_dame_front_facade: 0.1
  pantheon_exterior: 0.1
  piazza_san_marco: 0.1
  sacre_coeur: 0.1
  sagrada_familia: 0.1
  st_pauls_cathedral: 0.1
  st_peters_square: 0.1
  taj_mahal: 0.1
  temple_nara_japan: 0.1
  trevi_fountain: 0.1

solver_parameters:
  keypoint_number_threshold: 7
  ransac_reproj_threshold: 0.25
  ransac_confidence: 0.99999
  ransac_max_iters: 100000
